### ISSUE TITLE
CSRF tokens for single-page applications

### ISSUE THREAD

**Issue by maziarz** [tomchristie/apistar#53]
Similar to Django it would be interesting to have a CSRF mechanism for single-page applications running on client-side, eg. via a `/csrf-token` endpoint.

**Comment by tomchristie** [comment]
CSRF protection will be on the roadmap, but it only makes sense for us to think about this once we also get to the point that we're looking into adding session authentication support (since CSRF is about protecting session authenticated requests)

There's a number of pre-requisities that we'd need to tackle before this becomes relevant, so I'm going to close this off for now as not yet directly actionable.
