### ISSUE TITLE
Decorators for authentication and permsissions

### ISSUE THREAD

**Issue by maziarz** [tomchristie/apistar#59]
What are the thoughts on decorators? I am gradually working authentication/permissions into my API and was not sure which approach was planned for apistar.

**Comment by tomchristie** [comment]
It's most likely that views will be 'annotated', rather than having the function wrapped up in extra behavior.

    @annotate(auth=..., permissions=...)
    def my_view(...) {
    }

    my_view.auth == ...  # True
    my_view.permisions == ...  # True

We might also have a class based method of being able to compose and reuse annotation groups. That'll differ from, say, REST framework, in that it'd only be able being able to compose attributes, rather than class based views with overridable methods.

For now anything related to authentication or permissions needs to be coded into reusable components or into the view itself.
